### ISSUE TITLE
Add sync: Panic on adding a sync path

### ISSUE THREAD

**Issue by FabianK1991** [covexo/devspace#161]
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
        panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running, locked to thread]:
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.handleErr(0xc0426bf9d0)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/yaml.go:249 +0xa0
panic(0x1713540, 0x1d1fbc0)
        D:/Programme/Go/src/runtime/panic.go:502 +0x237
reflect.valueInterface(0x187a760, 0xc0428f6a30, 0xcc, 0x1713501, 0x1713501, 0x0)
        D:/Programme/Go/src/reflect/value.go:959 +0x1c8
reflect.Value.Interface(0x187a760, 0xc0428f6a30, 0xcc, 0x1713540, 0xc04249a610)
        D:/Programme/Go/src/reflect/value.go:948 +0x4b
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x187a760, 0xc0428f6a30, 0xcc)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:90 +0x7b
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).structv.func1()
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:198 +0x252
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc042f94840, 0x0, 0x0, 0xc0426becc8)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:228 +0x155
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).structv(0xc042f94840, 0x0, 0x0, 0x1a1a460, 0xc0428f6a20, 0x99)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:185 +0xfe
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x1a1a460, 0xc0428f6a20, 0x99)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:132 +0x688
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x17814e0, 0xc04249a000, 0x194)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:119 +0x5f3
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).slicev(0xc042f94840, 0x0, 0x0, 0x16d4260, 0xc0428f6a40, 0x97)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:244 +0x206
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x16d4260, 0xc0428f6a40, 0x97)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:138 +0x36a
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x17814e0, 0xc04249a5f0, 0x94)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:119 +0x5f3
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mapv.func1()
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:165 +0x19d
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc042f94840, 0x0, 0x0, 0xc0426bf318)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:228 +0x155
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mapv(0xc042f94840, 0x0, 0x0, 0x17c45e0, 0xc0426e3980, 0x15)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:160 +0x9c
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x17c45e0, 0xc0426e3980, 0x15)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:121 +0x5b0
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x17814e0, 0xc04249a490, 0x94)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:119 +0x5f3
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mapv.func1()
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:165 +0x19d
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc042f94840, 0x0, 0x0, 0xc0426bf6b8)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:228 +0x155
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).mapv(0xc042f94840, 0x0, 0x0, 0x17c45e0, 0xc0426e38f0, 0x15)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:160 +0x9c
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc042f94840, 0x0, 0x0, 0x17c45e0, 0xc0426e38f0, 0x15)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:121 +0x5b0
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.(*encoder).marshalDoc(0xc042f94840, 0x0, 0x0, 0x17c45e0, 0xc0426e38f0, 0x15)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/encode.go:80 +0x128
github.com/covexo/devspace/vendor/gopkg.in/yaml%2ev2.Marshal(0x17c45e0, 0xc0426e38f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/gopkg.in/yaml.v2/yaml.go:203 +0xe7
github.com/covexo/devspace/pkg/devspace/config/configutil.SaveConfig(0x1698a40, 0x2ca0ae8)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:51 +0x4f4
github.com/covexo/devspace/cmd.(*AddCmd).RunAddSync(0xc0427386f0, 0xc042f84a00, 0xc0420439c0, 0x0, 0x4)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/cmd/add.go:149 +0x40d
github.com/covexo/devspace/cmd.(*AddCmd).RunAddSync-fm(0xc042f84a00, 0xc0420439c0, 0x0, 0x4)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/cmd/add.go:80 +0x59
github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).execute(0xc042f84a00, 0xc042043940, 0x4, 0x4, 0xc042f84a00, 0xc042043940)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:766 +0x2c8
github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2c6d6a0, 0x1a4fde9, 0x7, 0x1b08625)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:852 +0x311
github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).Execute(0x2c6d6a0, 0x10, 0x0)
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/covexo/devspace/cmd.Execute()
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/cmd/root.go:39 +0x98
main.main()
        D:/Programmieren/go-workspace/src/github.com/covexo/devspace/main.go:15 +0x45
```

**Comment by LukasGentele** [comment]
should be resolved in #163
