### ISSUE TITLE
Config test fails.

### ISSUE THREAD

**Issue by 1522784** [covexo/devspace#232]
Whenever I run the config test, sometimes this error appears:

> Running tool: C:\Program Files\go\bin\go.exe test -timeout 30s github.com\covexo\devspace\pkg\devspace\config\configutil -run ^TestGetConfigOverwriteOnly$
> 
> --- FAIL: TestGetConfigOverwriteOnly (0.00s)
> panic: interface conversion: interface {} is int, not string [recovered]
> 	panic: interface conversion: interface {} is int, not string
> 
> goroutine 19 [running]:
> testing.tRunner.func1(0xc0422020f0)
> 	C:/Program Files/go/src/testing/testing.go:711 +0x2d9
> panic(0xbb2460, 0xc042245cc0)
> 	C:/Program Files/go/src/runtime/panic.go:491 +0x291
> github.com/covexo/devspace/pkg/devspace/config/configutil.getConfigAndOverwriteMaps(0xb514a0, 0xc042070380, 0xb514a0, 0xc0420704d0, 0xb514a0, 0xc0420703a8, 0xb514a0, 0x0, 0xb32f15, 0x17, ...)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:161 +0x21c5
> github.com/covexo/devspace/pkg/devspace/config/configutil.getConfigAndOverwriteMaps(0xb49160, 0xc0421e6b20, 0xb49160, 0xc0421e6680, 0xb49160, 0xc0421e6d00, 0xb49160, 0xc0421e6940, 0xb29848, 0xe, ...)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:217 +0x12c7
> github.com/covexo/devspace/pkg/devspace/config/configutil.getConfigAndOverwriteMaps(0xb48fa0, 0xc0421e6ae0, 0xb48fa0, 0xc0421e6640, 0xb48fa0, 0xc0421e6cc0, 0xb48fa0, 0xc0421e6900, 0xb363dd, 0x19, ...)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:217 +0x12c7
> github.com/covexo/devspace/pkg/devspace/config/configutil.getConfigAndOverwriteMaps(0xb48f60, 0xc0421e9560, 0xb48f60, 0xc0421e9380, 0xb48f60, 0xc0421e95f0, 0xb48f60, 0xc0421e93e0, 0xe5f40c39b3e46198, 0xc2c640, ...)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:217 +0x12c7
> github.com/covexo/devspace/pkg/devspace/config/configutil.SaveConfig(0xc000000000, 0xcb9fa0)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/save.go:27 +0x567
> github.com/covexo/devspace/pkg/devspace/config/configutil.TestGetConfigOverwriteOnly(0xc0422020f0)
> 	C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/config/configutil/get_test.go:62 +0x1df
> testing.tRunner(0xc0422020f0, 0xcb9fa8)
> 	C:/Program Files/go/src/testing/testing.go:746 +0xd7
> created by testing.(*T).Run
> 	C:/Program Files/go/src/testing/testing.go:789 +0x2e5
> FAIL	github.com/covexo/devspace/pkg/devspace/config/configutil	0.178s
> Error: Tests failed.

It should be easy to fix because the stack trace and the error message tell a lot about this issue. It always happens in TestGetConfigOverwriteOnly and happened once in TestGetConfigGlobalOnly.

**Comment by 1522784** [comment]
In the values map the test adds a key-value-pair with an int as the key. Some extra debug logs show, that this triggeres this panic. If the panic occurres, the key is always this  number. But if the key is this number, the error doesn't automatically appear.
```
			log.Info(key)
			yamlKey := getYamlKey(key.(string))
```

> [INFO]   0
> [INFO]   globalConfigMapKey
> [INFO]   globalConfigMapKey
> [INFO]   globalConfigMapKey
> [INFO]   globalConfigMapKey
> [INFO]   localConfigMapKey
> [INFO]   0
> --- FAIL: TestGetConfigOverwriteOnly (0.00s)
> panic: interface conversion: interface {} is int, not string [recovered]
> 	panic: interface conversion: interface {} is int, not string
