### ISSUE TITLE
nil pointer panic at devspace up

### ISSUE THREAD

**Issue by 1522784** [covexo/devspace#287]
Devspace up is right now really unreliable. Sometimes it works perfectly, sometimes it runs into issues of other tools like minikube for example, but this time it was a nil pointer panic, that terminated the command. Directly after the questions(no logs other than waiting in between) this happened:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x12ab246]
> 
> goroutine 1 [running, locked to thread]:
> github.com/covexo/devspace/pkg/devspace/deploy/helm.NewClient(0xc000ffae10, 0x1cb6500, 0x0, 0x0, 0x0)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/pkg/devspace/deploy/helm/client.go:82 +0x236
> github.com/covexo/devspace/cmd.(*UpCmd).initHelm(0xc0007026c0)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/cmd/up.go:366 +0x94
> github.com/covexo/devspace/cmd.(*UpCmd).Run(0xc0007026c0, 0xc000f66c80, 0x3329db8, 0x0, 0x0)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/cmd/up.go:143 +0x259
> github.com/covexo/devspace/cmd.(*UpCmd).Run-fm(0xc000f66c80, 0x3329db8, 0x0, 0x0)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/cmd/up.go:94 +0x59
> github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).execute(0xc000f66c80, 0x3329db8, 0x0, 0x0, 0xc000f66c80, 0x3329db8)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:766 +0x2d3
> github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x32ee380, 0x180000, 0x0, 0x17ef8c0)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:852 +0x304
> github.com/covexo/devspace/vendor/github.com/spf13/cobra.(*Command).Execute(0x32ee380, 0xc0006eff30, 0x40c50f)
>         C:/Users/covexo/go/src/github.com/covexo/devspace/vendor/github.com/spf13/cobra/command.go:800 +0x32
> github.com/covexo/devspace/cmd.Execute()
>         C:/Users/covexo/go/src/github.com/covexo/devspace/cmd/root.go:39 +0x90
> main.main()
>         C:/Users/covexo/go/src/github.com/covexo/devspace/main.go:16 +0x45

My answers were:
(Enter)
no
(Enter)
(Enter)
(Enter)
(Enter)

**Comment by 1522784** [comment]
I did a full reset before that.
